import AppKit
import SwiftUI

/// Hey AI brand tokens and the logo mark. See brand/BRAND.md.
enum Brand {
    static let ink = Color(red: 0x1B / 255, green: 0x1A / 255, blue: 0x2E / 255)
    static let paper = Color.white
    static let mist = Color(red: 0xF0 / 255, green: 0xF1 / 255, blue: 0xF6 / 255)
    /// Only for words you say out loud, and the mark on ink.
    static let highlight = Color(red: 0xFF / 255, green: 0xD8 / 255, blue: 0x4D / 255)
    static let signal = Color(red: 0x4B / 255, green: 0x4B / 255, blue: 0xE6 / 255)
    static let graphite = Color(red: 0x5C / 255, green: 0x5B / 255, blue: 0x70 / 255)

    static let nsInk = NSColor(srgbRed: 0x1B / 255, green: 0x1A / 255, blue: 0x2E / 255, alpha: 1)
    static let nsHighlight = NSColor(srgbRed: 0xFF / 255, green: 0xD8 / 255, blue: 0x4D / 255, alpha: 1)
    /// Signal, lightened on dark backgrounds (#9C9CFF), per BRAND.md.
    static let nsSignal = NSColor(name: nil) { appearance in
        appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
            ? NSColor(srgbRed: 0x9C / 255, green: 0x9C / 255, blue: 0xFF / 255, alpha: 1)
            : NSColor(srgbRed: 0x4B / 255, green: 0x4B / 255, blue: 0xE6 / 255, alpha: 1)
    }

    /// A small Highlight pill with Ink text: how the brand marks a phrase you say, sized
    /// to sit in a menu item.
    static func phrasePill(_ text: String, size: CGFloat = 13) -> NSImage {
        let font = NSFont.systemFont(ofSize: size, weight: .medium)
        let attributes: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: nsInk]
        let textSize = (text as NSString).size(withAttributes: attributes)
        let pad = CGSize(width: 5, height: 1)
        let pillSize = NSSize(width: ceil(textSize.width + pad.width * 2), height: ceil(textSize.height + pad.height * 2))
        let image = NSImage(size: pillSize, flipped: false) { bounds in
            nsHighlight.setFill()
            NSBezierPath(roundedRect: bounds, xRadius: 4, yRadius: 4).fill()
            (text as NSString).draw(at: NSPoint(x: pad.width, y: pad.height), withAttributes: attributes)
            return true
        }
        image.accessibilityDescription = text
        return image
    }

    /// The mark: an opening quote outlined from Unbounded Black (SIL OFL), in font units
    /// with y pointing down. Generated by brand/scripts/outline_logo.py.
    private static let markData = "M587 -750 475 -516 459 -610Q498 -610 528.5 -592.0Q559 -574 577.0 -543.5Q595 -513 595 -476Q595 -439 577.0 -409.0Q559 -379 528.0 -361.0Q497 -343 459 -343Q422 -343 391.0 -361.0Q360 -379 342.0 -409.5Q324 -440 324 -478Q324 -513 341.5 -552.5Q359 -592 401 -651L471 -750ZM283 -750 171 -516 155 -610Q194 -610 224.5 -592.0Q255 -574 273.0 -543.5Q291 -513 291 -476Q291 -439 273.0 -409.0Q255 -379 224.0 -361.0Q193 -343 155 -343Q118 -343 87.0 -361.0Q56 -379 38.0 -409.5Q20 -440 20 -478Q20 -513 37.5 -552.5Q55 -592 97 -651L167 -750Z"
    private static let markBounds = CGRect(x: 20, y: -750, width: 575, height: 407)
    private static let markOutline: CGPath = SVGPath.parse(markData)

    /// "Hey AI" set in Unbounded Bold, outlined the same way.
    private static let wordmarkData = "M69.6005859375 -750.0H277.197509765625V0.0H69.6005859375ZM660.4013671875 -750.0H867.998291015625V0.0H660.4013671875ZM185.5987548828125 -472.5985107421875H746.200439453125V-289.4012451171875H185.5987548828125ZM1318.5994873046875 16.39990234375Q1214.7996826171875 16.39990234375 1133.2998657226562 -21.7000732421875Q1051.800048828125 -59.800048828125 1004.8001708984375 -128.29998779296875Q957.80029296875 -196.7999267578125 957.80029296875 -287.599853515625Q957.80029296875 -377.3997802734375 1002.900146484375 -444.79974365234375Q1048.0 -512.19970703125 1126.5997924804688 -549.9996948242188Q1205.1995849609375 -587.7996826171875 1304.3994140625 -587.7996826171875Q1406.59912109375 -587.7996826171875 1479.3989868164062 -543.499755859375Q1552.1988525390625 -499.1998291015625 1591.3988037109375 -418.29998779296875Q1630.5987548828125 -337.400146484375 1630.5987548828125 -227.400390625H1123.397705078125V-350.3994140625H1515.80078125L1449.0008544921875 -307.399658203125Q1445.40087890625 -350.8001708984375 1427.3006591796875 -381.2005615234375Q1409.200439453125 -411.6009521484375 1379.6000366210938 -427.701171875Q1349.9996337890625 -443.8013916015625 1309.1990966796875 -443.8013916015625Q1264.1986083984375 -443.8013916015625 1231.898193359375 -425.90118408203125Q1199.5977783203125 -408.0009765625 1181.8975219726562 -376.40057373046875Q1164.197265625 -344.8001708984375 1164.197265625 -303.3995361328125Q1164.197265625 -249.399169921875 1188.4974365234375 -211.49884033203125Q1212.797607421875 -173.5985107421875 1260.1978149414062 -153.59832763671875Q1307.5980224609375 -133.59814453125 1376.59814453125 -133.59814453125Q1439.7982177734375 -133.59814453125 1502.3984375 -150.19830322265625Q1564.9986572265625 -166.7984619140625 1615.7987060546875 -197.19873046875V-67.2001953125Q1556.5989990234375 -27.2001953125 1481.4990234375 -5.400146484375Q1406.3990478515625 16.39990234375 1318.5994873046875 16.39990234375ZM1873.9984130859375 181.39990234375Q1810.7989501953125 181.39990234375 1761.8992919921875 165.9000244140625Q1712.9996337890625 150.400146484375 1666.60009765625 117.6005859375V-23.9976806640625Q1713.5997314453125 6.0020751953125 1754.699462890625 19.10198974609375Q1795.7991943359375 32.201904296875 1844.7989501953125 32.201904296875Q1886.39892578125 32.201904296875 1918.0989379882812 14.3018798828125Q1949.7989501953125 -3.59814453125 1970.198974609375 -51.998046875L2189.200439453125 -571.3997802734375H2406.397216796875L2131.9964599609375 11.201171875Q2102.5966796875 74.400634765625 2061.0970458984375 111.80035400390625Q2019.597412109375 149.2000732421875 1971.7977905273438 165.29998779296875Q1923.9981689453125 181.39990234375 1873.9984130859375 181.39990234375ZM1880.80078125 -53.3985595703125 1638.2000732421875 -571.3997802734375H1863.396728515625L2077.5980224609375 -53.3985595703125ZM2807.398681640625 -144.401123046875V-310.998779296875H3323.5989990234375V-144.401123046875ZM3205.796630859375 -750.0 3547.1973876953125 0.0H3325.8006591796875L3039.5989990234375 -661.6015625H3099.5986328125L2813.39697265625 0.0H2592.000244140625L2933.4010009765625 -750.0ZM3617.6005859375 -750.0H3825.197509765625V0.0H3617.6005859375Z"
    private static let wordmarkBounds = CGRect(x: 69.6, y: -750.0, width: 3755.6, height: 931.4)
    private static let wordmarkOutline: CGPath = SVGPath.parse(wordmarkData)

    /// The mark scaled to fit `rect` (aspect-fit, centered).
    static func markPath(in rect: CGRect) -> CGPath { fit(markOutline, markBounds, in: rect) }

    static func wordmarkPath(in rect: CGRect) -> CGPath { fit(wordmarkOutline, wordmarkBounds, in: rect) }

    /// Width ÷ height of the wordmark, for sizing frames.
    static let wordmarkAspect = wordmarkBounds.width / wordmarkBounds.height

    private static func fit(_ outline: CGPath, _ bounds: CGRect, in rect: CGRect) -> CGPath {
        let scale = min(rect.width / bounds.width, rect.height / bounds.height)
        let w = bounds.width * scale, h = bounds.height * scale
        var t = CGAffineTransform(translationX: rect.midX - w / 2, y: rect.midY - h / 2)
            .scaledBy(x: scale, y: scale)
            .translatedBy(x: -bounds.minX, y: -bounds.minY)
        return outline.copy(using: &t) ?? outline
    }

    enum MenuState { case listening, paused, heard, dictating }

    /// Template image for the menu bar (macOS tints it for light/dark menu bars).
    static func menuBarImage(_ state: MenuState) -> NSImage {
        let size = NSSize(width: 24, height: 16)
        let image = NSImage(size: size, flipped: true) { bounds in
            guard let ctx = NSGraphicsContext.current?.cgContext else { return false }
            ctx.setFillColor(NSColor.black.cgColor)
            switch state {
            case .listening:
                ctx.addPath(markPath(in: bounds.insetBy(dx: 2, dy: 1.5)))
                ctx.fillPath()
            case .paused:
                ctx.setAlpha(0.35)
                ctx.addPath(markPath(in: bounds.insetBy(dx: 2, dy: 1.5)))
                ctx.fillPath()
                ctx.setAlpha(1)
                ctx.setStrokeColor(NSColor.black.cgColor)
                ctx.setLineWidth(1.6)
                ctx.setLineCap(.round)
                ctx.move(to: CGPoint(x: 3, y: 1.5))
                ctx.addLine(to: CGPoint(x: 21, y: 14.5))
                ctx.strokePath()
            case .heard:
                // The mark knocked out of a filled pill: "I heard you".
                let pill = CGPath(roundedRect: bounds.insetBy(dx: 0.5, dy: 0.5), cornerWidth: 5, cornerHeight: 5, transform: nil)
                ctx.addPath(pill)
                ctx.fillPath()
                ctx.setBlendMode(.destinationOut)
                ctx.addPath(markPath(in: bounds.insetBy(dx: 5, dy: 3.5)))
                ctx.fillPath()
            case .dictating:
                // Smaller mark plus a dot: words are going into Claude Code.
                ctx.addPath(markPath(in: CGRect(x: 0.5, y: 2.5, width: 15, height: 11)))
                ctx.fillPath()
                ctx.fillEllipse(in: CGRect(x: 18, y: 9, width: 5, height: 5))
            }
            return true
        }
        image.isTemplate = true
        image.accessibilityDescription = "Hey AI"
        return image
    }
}

/// The mark as a SwiftUI shape.
struct BrandMark: Shape {
    func path(in rect: CGRect) -> Path { Path(Brand.markPath(in: rect)) }
}

/// The "Hey AI" wordmark as a SwiftUI shape.
struct BrandWordmark: Shape {
    func path(in rect: CGRect) -> Path { Path(Brand.wordmarkPath(in: rect)) }
}

/// Minimal SVG path-data reader for the absolute M/L/H/V/Q/C/Z commands fontTools writes,
/// including implicit repeats ("M x y x y" = move, then line).
enum SVGPath {
    static func parse(_ data: String) -> CGPath {
        let path = CGMutablePath()
        var tokens: [String] = []
        var number = ""
        for ch in data {
            if ch.isLetter && ch != "e" {
                if !number.isEmpty { tokens.append(number); number = "" }
                tokens.append(String(ch))
            } else if ch == " " || ch == "," {
                if !number.isEmpty { tokens.append(number); number = "" }
            } else if ch == "-" && !number.isEmpty && number.last != "e" {
                tokens.append(number); number = "-"
            } else {
                number.append(ch)
            }
        }
        if !number.isEmpty { tokens.append(number) }

        var i = 0
        var command = "M"
        var current = CGPoint.zero
        func next() -> CGFloat { defer { i += 1 }; return CGFloat(Double(tokens[i]) ?? 0) }
        func point() -> CGPoint { CGPoint(x: next(), y: next()) }
        while i < tokens.count {
            if let c = tokens[i].first, c.isLetter { command = tokens[i]; i += 1 }
            switch command {
            case "M": current = point(); path.move(to: current); command = "L"
            case "L": current = point(); path.addLine(to: current)
            case "H": current = CGPoint(x: next(), y: current.y); path.addLine(to: current)
            case "V": current = CGPoint(x: current.x, y: next()); path.addLine(to: current)
            case "Q": let c = point(); current = point(); path.addQuadCurve(to: current, control: c)
            case "C": let c1 = point(), c2 = point(); current = point(); path.addCurve(to: current, control1: c1, control2: c2)
            case "Z", "z": path.closeSubpath()
            default: i += 1
            }
        }
        return path
    }
}
